<?php

use Drupal\views\ViewExecutable;

/**
* Implements hook_theme().
*/
function islandora_whole_object_theme($existing, $type, $theme, $path) {
  return [
    'islandora_whole_object_block_pre' => [
      'variables' => ['content' => NULL],
    ],
    'islandora_whole_object_block_media' => [
      'variables' => ['content' => NULL],
    ],
    'islandora_whole_object_block_properties' => [
      'variables' => ['content' => NULL],
    ],
  ];
}

/**
* Implements hook_page_attachments().
*/
function islandora_whole_object_page_attachments(array &$attachments) {
  if (\Drupal::routeMatch()->getRouteName() == 'islandora_whole_object.whole_object') {
    $current_path = \Drupal::service('path.current')->getPath();
    $path_args = explode('/', $current_path);
    if ($path_args[4] == 'jsonldvisualized') {
      $node = \Drupal::routeMatch()->getParameter('node');
      $nid = $node->id();
      $attachments['#attached']['library'][] = 'islandora_whole_object/islandora_whole_object';
      // See https://github.com/mjordan/islandora_whole_object/issues/1.
      // $attachments['#attached']['library'][] = 'islandora_whole_object/jsonld-vis';
      $attachments['#attached']['drupalSettings']['islandora_whole_object']['nid'] = $nid;
    }
  }
}

/**
 * Implements hook_views_pre_render().
 *
 * Note: this doesn't work with the Media block.
 */
function islandora_whole_object_views_pre_render(ViewExecutable $view) {
  if (\Drupal::routeMatch()->getRouteName() == 'islandora_whole_object.whole_object') {
    if ($view->id() == 'media_of' && $view->current_display == 'page_1') {
      unset($view->field['media_bulk_form']);
      unset($view->field['operations']);
    }
  }
}
