<?php

use Drupal\views\ViewExecutable;

/**
* Implements hook_theme().
*/
function islandora_whole_object_theme($existing, $type, $theme, $path) {
  return [
    'islandora_whole_object_content' => [
      'variables' => ['format' => NULL, 'whole_object' => NULL, 'heading' => NULL],
    ],
  ];
}

/**
* Default preprocessor function for the islandora_whole_object theme hook.
*/
function template_preprocess_islandora_whole_object_content(&$variables) {
  $variables['attributes'] = [
    'id' => ['islandora_whole_object'],
  ];
}

/**
* Implements hook_page_attachments().
*/
function islandora_whole_object_page_attachments(array &$attachments) {
  if (\Drupal::routeMatch()->getRouteName() == 'islandora_whole_object.whole_object') {
    $current_path = \Drupal::service('path.current')->getPath();
    $path_args = explode('/', $current_path);
    if ($path_args[4] == 'jsonldvisualized') {
      $node = \Drupal::routeMatch()->getParameter('node');
      $nid = $node->id();
      $attachments['#attached']['library'][] = 'islandora_whole_object/islandora_whole_object';
      // See https://github.com/mjordan/islandora_whole_object/issues/1.
      // $attachments['#attached']['library'][] = 'islandora_whole_object/jsonld-vis';
      $attachments['#attached']['drupalSettings']['islandora_whole_object']['nid'] = $nid;
    }
  }
}

/**
 * Implements hook_views_pre_render().
 */
function islandora_whole_object_views_pre_render(ViewExecutable $view) {
  if (\Drupal::routeMatch()->getRouteName() == 'islandora_whole_object.whole_object') {
    if ($view->id() == 'media_of' && $view->current_display) {
      unset($view->field['media_bulk_form']);
      unset($view->field['operations']);
    }
  }
}
